#!/usr/bin/env node
import { createHash, randomUUID } from 'node:crypto';
import { cp, mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const workspace = join(root, '.game-graph'), drafts = join(workspace, '.agent-drafts'), lock = join(workspace, '.agent-tools.lock');
const fail = (code, message, details = {}) => { throw Object.assign(new Error(message), { code, details }); };
const hash = value => createHash('sha256').update(value).digest('hex');
const json = async path => { try { return { path, raw: await readFile(path, 'utf8') }; } catch (error) { fail(error.code === 'ENOENT' ? 'WORKSPACE_FILE_MISSING' : 'WORKSPACE_READ_FAILED', `无法读取 ${path}`); } };
const parse = async path => { const file = await json(path); try { return { ...file, value: JSON.parse(file.raw), revision: hash(file.raw) }; } catch { fail('INVALID_JSON', `JSON 无法解析：${path}`); } };
const args = values => { const positionals = [], options = {}; for (let i = 0; i < values.length; i++) { const item = values[i]; if (!item.startsWith('--')) { positionals.push(item); continue; } const key = item.slice(2), value = values[++i]; if (!key || value === undefined || value.startsWith('--') || Object.hasOwn(options, key)) fail('TOOL_INVALID', `参数无效：${item}`); options[key] = value; } return { positionals, options }; };
const emit = value => process.stdout.write(JSON.stringify(value, null, 2) + '\n');
const readMechanicPaths = async directory => { const entries = await readdir(directory, { withFileTypes: true }); const found = []; for (const entry of entries) { const path = join(directory, entry.name); if (entry.isDirectory()) found.push(...await readMechanicPaths(path)); else if (entry.isFile() && entry.name.endsWith('.mechanic.json')) found.push(path); } return found; };
async function snapshot() { const manifest = await parse(join(workspace, 'workspace.json')), definitions = await parse(join(workspace, 'definitions.graph.json')); const paths = await readMechanicPaths(join(workspace, 'mechanics')); const mechanics = await Promise.all(paths.map(parse)); const nodes = definitions.value.nodes ?? []; const edges = mechanics.flatMap(file => (file.value.edges ?? []).map(edge => ({ ...edge, id: `${file.value.id}/${edge.id}`, origin: { mechanicId: file.value.id, edgeId: edge.id } }))); const revision = hash([manifest.raw, definitions.raw, ...mechanics.map(item => item.raw)].join('\n'));
  return { manifest, definitions, mechanics, nodes, edges, revision, nodeMap: new Map(nodes.map(node => [node.id, node])) }; }
const operator = edge => edge.relation === 'specializes' ? 'is-a>' : edge.sign === 1 ? '+>' : edge.sign === -1 ? '->' : '?>';
function resolveNode(nodes, key) { const norm = key.trim().toLowerCase(); const id = nodes.find(node => node.id.toLowerCase() === norm); if (id) return { status: 'resolved', node: id, matchedBy: 'id' }; const candidates = nodes.filter(node => node.label?.trim().toLowerCase() === norm || (node.aliases ?? []).some(alias => alias.trim().toLowerCase() === norm)); if (candidates.length === 1) return { status: 'resolved', node: candidates[0], matchedBy: candidates[0].label?.trim().toLowerCase() === norm ? 'label' : 'alias' }; return candidates.length ? { status: 'ambiguous', candidates: candidates.map(node => ({ id: node.id, label: node.label })) } : { status: 'not_found' }; }
function paths(edges, from, to, maxDepth = 16) { const out = new Map(); for (const edge of edges) (out.get(edge.source) ?? out.set(edge.source, []).get(edge.source)).push(edge); const queue = [{ ids: [from], steps: [] }], result = []; for (let i = 0; i < queue.length; i++) { const current = queue[i]; if (current.ids.at(-1) === to && current.steps.length) { result.push(current); continue; } if (current.steps.length >= maxDepth) continue; for (const edge of out.get(current.ids.at(-1)) ?? []) if (!current.ids.includes(edge.target)) queue.push({ ids: [...current.ids, edge.target], steps: [...current.steps, edge] }); } return result.sort((a,b) => a.steps.length - b.steps.length || a.ids.join('\0').localeCompare(b.ids.join('\0'))); }
function compact(path, map) { const steps = path.steps.map(edge => ({ from: edge.source, to: edge.target, operator: operator(edge), origin: edge.origin })); const taxonomy = path.steps.some(edge => edge.relation === 'specializes'); let sign = 1; for (const edge of path.steps) if (edge.relation === 'influence') sign = sign === 'random' || edge.sign === 'random' ? 'random' : sign * edge.sign; return { length: steps.length, nodes: path.ids.map(id => ({ id, label: map.get(id)?.label ?? id })), steps, chain: path.ids.map((id, i) => i ? `${steps[i - 1].operator} ${id}` : id).join(' '), kind: taxonomy ? (path.steps.every(edge => edge.relation === 'specializes') ? 'taxonomy' : 'mixed') : 'influence', effect: taxonomy ? null : sign === 1 ? 'positive' : sign === -1 ? 'negative' : 'random' }; }
async function withLock(fn) { try { await writeFile(lock, String(process.pid), { flag: 'wx' }); } catch { fail('WORKSPACE_LOCKED', '已有 JSON 工具正在写入工作区'); } try { return await fn(); } finally { await rm(lock, { force: true }); } }
async function openDraft(mechanicId) { const data = await snapshot(), mechanic = data.mechanics.find(item => item.value.id === mechanicId); if (!mechanic) fail('MECHANIC_NOT_FOUND', `机制不存在：${mechanicId}`); await mkdir(drafts, { recursive: true }); const id = randomUUID(), folder = join(drafts, id); await mkdir(folder); const definitionsPath = join(folder, 'definitions.graph.json'), mechanicPath = join(folder, 'mechanic.json'); await cp(data.definitions.path, definitionsPath); await cp(mechanic.path, mechanicPath); const meta = { id, workspaceId: data.manifest.value.id, mechanicId, definitionsRevision: data.definitions.revision, mechanicRevision: mechanic.revision }; await writeFile(join(folder, 'draft.json'), JSON.stringify(meta, null, 2) + '\n'); return { draftId: id, draftPath: folder, definitionsPath, mechanicPath, revision: data.revision }; }
async function saveDraft(id) { const folder = join(drafts, id); if (relative(drafts, folder).startsWith('..' + sep)) fail('DRAFT_NOT_FOUND', '草稿不存在'); const meta = (await parse(join(folder, 'draft.json'))).value, draftDefinitions = await parse(join(folder, 'definitions.graph.json')), draftMechanic = await parse(join(folder, 'mechanic.json'));
  return withLock(async () => { const data = await snapshot(), mechanic = data.mechanics.find(item => item.value.id === meta.mechanicId); if (!mechanic || data.manifest.value.id !== meta.workspaceId || data.definitions.revision !== meta.definitionsRevision || mechanic.revision !== meta.mechanicRevision) fail('RESOURCE_REVISION_CONFLICT', '保存前 canonical 已变化；草稿已保留'); if (draftMechanic.value.id !== meta.mechanicId) fail('DRAFT_IDENTITY_MISMATCH', '草稿机制 ID 与目标不一致'); const tempDefinitions = data.definitions.path + '.' + randomUUID() + '.tmp', tempMechanic = mechanic.path + '.' + randomUUID() + '.tmp'; await writeFile(tempDefinitions, draftDefinitions.raw); await writeFile(tempMechanic, draftMechanic.raw); await rename(tempDefinitions, data.definitions.path); await rename(tempMechanic, mechanic.path); try { await snapshot(); } catch (error) { fail('SAVE_UNCERTAIN', '提交后回读失败，请检查真实 JSON 状态', { cause: error.message }); } await rm(folder, { recursive: true, force: true }); return { saved: true, revision: (await snapshot()).revision, note: '仅提交 JSON；未执行网页校验、自动排版或文档导出。' }; }); }
async function main() { const { positionals, options } = args(process.argv.slice(2)), [command, action] = positionals; if (!command) fail('TOOL_INVALID', '需要命令'); const data = ['scopes','search','node','impact'].includes(command) ? await snapshot() : null;
  if (command === 'scopes') return { workspaceId: data.manifest.value.id, revision: data.revision, mechanics: data.mechanics.map(item => ({ id: item.value.id, name: item.value.name, file: relative(root, item.path) })) };
  if (command === 'search') { if (options.query) { const r = resolveNode(data.nodes, options.query); return r.status === 'resolved' ? { revision: data.revision, concept: r.node, matchedBy: r.matchedBy } : { revision: data.revision, resolution: r }; } if (!options.from || !options.to) fail('TOOL_INVALID', 'search 需要 --query 或 --from --to'); const a = resolveNode(data.nodes, options.from), b = resolveNode(data.nodes, options.to); if (a.status !== 'resolved' || b.status !== 'resolved') return { revision: data.revision, from: a, to: b, rules: null }; const direct = (x,y) => data.edges.filter(edge => edge.source === x.id && edge.target === y.id).map(edge => ({ id: edge.id, operator: operator(edge), ruleText: edge.ruleText ?? '', origin: edge.origin })); return { revision: data.revision, from: a.node, to: b.node, rules: { forward: direct(a.node,b.node), reverse: direct(b.node,a.node) } }; }
  if (command === 'impact') { if (!options.from || !options.to || !data.nodeMap.has(options.from) || !data.nodeMap.has(options.to)) fail('NODE_NOT_FOUND', 'impact 需要已有 --from 与 --to'); const result = paths(data.edges, options.from, options.to, Number(options['max-depth'] ?? 16)).map(path => compact(path, data.nodeMap)); return { revision: data.revision, counts: { returned: result.length }, paths: result }; }
  if (command === 'node') { if (!options.id || !data.nodeMap.has(options.id)) fail('NODE_NOT_FOUND', 'node 需要已有 --id'); const hops = Number(options.hops ?? 1), direction = options.direction ?? 'both', inbound = data.edges.map(edge => ({ ...edge, source: edge.target, target: edge.source })), pick = edges => paths(edges, options.id, '__never__', hops); const collect = edges => { const out = []; const walk = (id, depth, seen, steps) => { if (depth >= hops) return; for (const edge of edges.filter(item => item.source === id)) if (!seen.has(edge.target)) { const next = [...steps, edge]; out.push({ ids: [options.id, ...next.map(item => item.target)], steps: next }); walk(edge.target, depth + 1, new Set([...seen, edge.target]), next); } }; walk(options.id, 0, new Set([options.id]), []); return out.map(path => compact(path, data.nodeMap)); }; return { revision: data.revision, center: data.nodeMap.get(options.id), direction, paths: { ...(direction !== 'downstream' ? { upstream: collect(inbound) } : {}), ...(direction !== 'upstream' ? { downstream: collect(data.edges) } : {}) } }; }
  if (command === 'draft' && action === 'open') { if (!options.mechanic) fail('TOOL_INVALID', 'draft open 需要 --mechanic'); return openDraft(options.mechanic); }
  if (command === 'draft' && action === 'save') { if (!options.draft) fail('TOOL_INVALID', 'draft save 需要 --draft'); return saveDraft(options.draft); }
  fail('TOOL_INVALID', '仅支持 scopes/search/node/impact/draft open|save'); }
main().then(emit).catch(error => { process.stderr.write(JSON.stringify({ error: error.code ?? 'TOOL_FAILED', message: error.message, ...error.details }) + '\n'); process.exitCode = 1; });
